export const GET_ADMINS_FETCHING = 'GET_ADMINS_FETCHING';
export const GET_ADMINS_FULFILLED = 'GET_ADMINS_FULFILLED';
export const GET_ADMINS_REJECTED = 'GET_ADMINS_REJECTED';

export const GET_ADMIN_BY_ID_FETCHING = 'GET_ADMIN_BY_ID_FETCHING';
export const GET_ADMIN_BY_ID_FULFILLED = 'GET_ADMIN_BY_ID_FULFILLED';
export const GET_ADMIN_BY_ID_REJECTED = 'GET_ADMIN_BY_ID_REJECTED';

export const ADD_ADMIN_FETCHING = 'ADD_ADMIN_FETCHING';
export const ADD_ADMIN_FULFILLED = 'ADD_ADMIN_FULFILLED';
export const ADD_ADMIN_REJECTED = 'ADD_ADMIN_REJECTED';

export const DELETE_ADMIN_FETCHING = 'DELETE_ADMIN_FETCHING';
export const DELETE_ADMIN_FULFILLED = 'DELETE_ADMIN_FULFILLED';
export const DELETE_ADMIN_REJECTED = 'DELETE_ADMIN_REJECTED';

export const UPDATE_ADMIN_FETCHING = 'UPDATE_ADMIN_FETCHING';
export const UPDATE_ADMIN_FULFILLED = 'UPDATE_ADMIN_FULFILLED';
export const UPDATE_ADMIN_REJECTED = 'UPDATE_ADMIN_REJECTED';

export const SET_ADMIN = 'SET_ADMIN';

export const ADMIN_CLOSE_ERROR_MODAL = 'ADMIN_CLOSE_ERROR_MODAL';
// Applications

// Clients

//Interviews

//Positions

//Postulants

//Profiles

//Psychologists

//Sessions
