export const GET_ADMINS_FETCHING = 'GET_ADMINS_FETCHING';
export const GET_ADMINS_FULFILLED = 'GET_ADMINS_FULFILLED';
export const GET_ADMINS_REJECTED = 'GET_ADMINS_REJECTED';

export const GET_ADMIN_BY_ID_FETCHING = 'GET_ADMIN_BY_ID_FETCHING';
export const GET_ADMIN_BY_ID_FULFILLED = 'GET_ADMIN_BY_ID_FULFILLED';
export const GET_ADMIN_BY_ID_REJECTED = 'GET_ADMIN_BY_ID_REJECTED';

export const CREATE_ADMIN_FETCHING = 'CREATE_ADMIN_FETCHING';
export const CREATE_ADMIN_FULFILLED = 'CREATE_ADMIN_FULFILLED';
export const CREATE_ADMIN_REJECTED = 'CREATE_ADMIN_REJECTED';

export const DELETE_ADMIN_FETCHING = 'DELETE_ADMIN_FETCHING';
export const DELETE_ADMIN_FULFILLED = 'DELETE_ADMIN_FULFILLED';
export const DELETE_ADMIN_REJECTED = 'DELETE_ADMIN_REJECTED';

export const UPDATE_ADMIN_FETCHING = 'UPDATE_ADMIN_FETCHING';
export const UPDATE_ADMIN_FULFILLED = 'UPDATE_ADMIN_FULFILLED';
export const UPDATE_ADMIN_REJECTED = 'UPDATE_ADMIN_REJECTED';

export const ADMIN_CLOSE_ERROR_MODAL = 'ADMIN_CLOSE_ERROR_MODAL';
// Applications
export const GET_APPLICATIONS_FETCHING = 'GET_APPLICATIONS_FETCHING';
export const GET_APPLICATIONS_FULFILLED = 'GET_APPLICATIONS_FULFILLED';
export const GET_APPLICATIONS_REJECTED = 'GET_APPLICATIONS_REJECTED';

export const CREATE_APPLICATION_FETCHING = 'CREATE_APPLICATION_FETCHING';
export const CREATE_APPLICATION_FULFILLED = 'CREATE_APPLICATION_FULFILLED';
export const CREATE_APPLICATION_REJECTED = 'CREATE_APPLICATION_REJECTED';

export const DELETE_APPLICATION_FETCHING = 'DELETE_APPLICATION_FETCHING';
export const DELETE_APPLICATION_FULFILLED = 'DELETE_APPLICATION_FULFILLED';
export const DELETE_APPLICATION_REJECTED = 'DELETE_APPLICATION_REJECTED';

export const CLOSE_ERROR_MODAL_APPLICATIONS = 'CLOSE_ERROR_MODAL_APPLICATIONS';
// Clients

export const GET_CLIENTS_FETCHING = 'GET_CLIENTS_FETCHING';
export const GET_CLIENTS_FULFILLED = 'GET_CLIENTS_FULFILLED';
export const GET_CLIENTS_REJECTED = 'GET_CLIENTS_REJECTED';

export const GET_CLIENT_BY_ID_FETCHING = 'GET_CLIENT_BY_ID_FETCHING';
export const GET_CLIENT_BY_ID_FULFILLED = 'GET_CLIENT_BY_ID_FULFILLED';
export const GET_CLIENT_BY_ID_REJECTED = 'GET_CLIENT_BY_ID_REJECTED';

export const CREATE_CLIENT_FETCHING = 'CREATE_CLIENT_FETCHING';
export const CREATE_CLIENT_FULFILLED = 'CREATE_CLIENT_FULFILLED';
export const CREATE_CLIENT_REJECTED = 'CREATE_CLIENT_REJECTED';

export const UPDATE_CLIENT_FETCHING = 'UPDATE_CLIENT_FETCHING';
export const UPDATE_CLIENT_FULFILLED = 'UPDATE_CLIENT_FULFILLED';
export const UPDATE_CLIENT_REJECTED = 'UPDATE_CLIENT_REJECTED';

export const DELETE_CLIENT_FETCHING = 'DELETE_CLIENT_FETCHING';
export const DELETE_CLIENT_FULFILLED = 'DELETE_CLIENT_FULFILLED';
export const DELETE_CLIENT_REJECTED = 'DELETE_CLIENT_REJECTED';

export const CLOSE_ERROR_MODAL_CLIENTS = 'CLOSE_ERROR_MODAL_CLIENTS';

//Interviews
export const GET_INTERVIEWS_FETCHING = 'GET_INTERVIEWS_FETCHING';
export const GET_INTERVIEWS_FULFILLED = 'GET_INTERVIEWS_FULFILLED';
export const GET_INTERVIEWS_REJECTED = 'GET_INTERVIEWS_REJECTED';

export const GET_INTERVIEW_BY_ID_FETCHING = 'GET_INTERVIEW_BY_ID_FETCHING';
export const GET_INTERVIEW_BY_ID_FULFILLED = 'GET_INTERVIEW_BY_ID_FULFILLED';
export const GET_INTERVIEW_BY_ID_REJECTED = 'GET_INTERVIEW_BY_ID_REJECTED';

export const CREATE_INTERVIEW_FETCHING = 'CREATE_INTERVIEW_FETCHING';
export const CREATE_INTERVIEW_FULFILLED = 'CREATE_INTERVIEW_FULFILLED';
export const CREATE_INTERVIEW_REJECTED = 'CREATE_INTERVIEW_REJECTED';

export const UPDATE_INTERVIEW_FETCHING = 'UPDATE_INTERVIEW_FETCHING';
export const UPDATE_INTERVIEW_FULFILLED = 'UPDATE_INTERVIEW_FULFILLED';
export const UPDATE_INTERVIEW_REJECTED = 'UPDATE_INTERVIEW_REJECTED';

export const DELETE_INTERVIEW_FETCHING = 'DELETE_INTERVIEW_FETCHING';
export const DELETE_INTERVIEW_FULFILLED = 'DELETE_INTERVIEW_FULFILLED';
export const DELETE_INTERVIEW_REJECTED = 'DELETE_INTERVIEW_REJECTED';

export const CLOSE_ERROR_MODAL_INTERVIEWS = 'CLOSE_ERROR_MODAL_INTERVIEWS';
// Interviews

// Positions

// Postulants

// Profiles

// Psychologists
export const GET_POSITIONS_FETCHING = 'GET_POSITIONS_FETCHING';
export const GET_POSITIONS_FULFILLED = 'GET_POSITIONS_FULFILLED';
export const GET_POSITIONS_REJECTED = 'GET_POSITIONS_REJECTED';

export const GET_POSITION_BY_ID_FETCHING = 'GET_POSITION_BY_ID_FETCHING';
export const GET_POSITION_BY_ID_FULFILLED = 'GET_POSITION_BY_ID_FULFILLED';
export const GET_POSITION_BY_ID_REJECTED = 'GET_POSITION_BY_ID_REJECTED';

export const CREATE_POSITION_FETCHING = 'CREATE_POSITION_FETCHING';
export const CREATE_POSITION_FULFILLED = 'CREATE_POSITION_FULFILLED';
export const CREATE_POSITION_REJECTED = 'CREATE_POSITION_REJECTED';

export const UPDATE_POSITION_FETCHING = 'UPDATE_POSITION_FETCHING';
export const UPDATE_POSITION_FULFILLED = 'UPDATE_POSITION_FULFILLED';
export const UPDATE_POSITION_REJECTED = 'UPDATE_POSITION_REJECTED';

export const DELETE_POSITION_FETCHING = 'DELETE_POSITION_FETCHING';
export const DELETE_POSITION_FULFILLED = 'DELETE_POSITION_FULFILLED';
export const DELETE_POSITION_REJECTED = 'DELETE_POSITION_REJECTED';

export const CLOSE_ERROR_MODAL_POSITIONS = 'CLOSE_ERROR_MODAL_POSITIONS';

//Postulants

//Profiles
export const GET_PROFILES_FETCHING = 'GET_PROFILES_FETCHING';
export const GET_PROFILES_FULFILLED = 'GET_PROFILES_FULFILLED';
export const GET_PROFILES_REJECTED = 'GET_PROFILES_REJECTED';

export const GET_PROFILE_BY_ID_FETCHING = 'GET_PROFILE_BY_ID_FETCHING';
export const GET_PROFILE_BY_ID_FULFILLED = 'GET_PROFILE_BY_ID_FULFILLED';
export const GET_PROFILE_BY_ID_REJECTED = 'GET_PROFILE_BY_ID_REJECTED';

export const CREATE_PROFILE_FETCHING = 'CREATE_PROFILE_FETCHING';
export const CREATE_PROFILE_FULFILLED = 'CREATE_PROFILE_FULFILLED';
export const CREATE_PROFILE_REJECTED = 'CREATE_PROFILE_REJECTED';

export const UPDATE_PROFILE_FETCHING = 'UPDATE_PROFILE_FETCHING';
export const UPDATE_PROFILE_FULFILLED = 'UPDATE_PROFILE_FULFILLED';
export const UPDATE_PROFILE_REJECTED = 'UPDATE_PROFILE_REJECTED';

export const DELETE_PROFILE_FETCHING = 'DELETE_PROFILE_FETCHING';
export const DELETE_PROFILE_FULFILLED = 'DELETE_PROFILE_FULFILLED';
export const DELETE_PROFILE_REJECTED = 'DELETE_PROFILE_REJECTED';

export const CLOSE_ERROR_MODAL_PROFILES = 'CLOSE_ERROR_MODAL_PROFILES';

//Psychologists
export const GET_PSYCHOLOGISTS_FETCHING = 'GET_PSYCHOLOGISTS_FETCHING';
export const GET_PSYCHOLOGISTS_FULFILLED = 'GET_PSYCHOLOGISTS_FULFILLED';
export const GET_PSYCHOLOGISTS_REJECTED = 'GET_PSYCHOLOGISTS_REJECTED';

export const GET_PSYCHOLOGIST_BY_ID_FETCHING = 'GET_PSYCHOLOGIST_BY_ID_FETCHING';
export const GET_PSYCHOLOGIST_BY_ID_FULFILLED = 'GET_PSYCHOLOGIST_BY_ID_FULFILLED';
export const GET_PSYCHOLOGIST_BY_ID_REJECTED = 'GET_PSYCHOLOGIST_BY_ID_REJECTED';

export const CREATE_PSYCHOLOGIST_FETCHING = 'CREATE_PSYCHOLOGIST_FETCHING';
export const CREATE_PSYCHOLOGIST_FULFILLED = 'CREATE_PSYCHOLOGIST_FULFILLED';
export const CREATE_PSYCHOLOGIST_REJECTED = 'CREATE_PSYCHOLOGIST_REJECTED';

export const UPDATE_PSYCHOLOGIST_FETCHING = 'UPDATE_PSYCHOLOGIST_FETCHING';
export const UPDATE_PSYCHOLOGIST_FULFILLED = 'UPDATE_PSYCHOLOGIST_FULFILLED';
export const UPDATE_PSYCHOLOGIST_REJECTED = 'UPDATE_PSYCHOLOGIST_REJECTED';

export const DELETE_PSYCHOLOGIST_FETCHING = 'DELETE_PSYCHOLOGIST_FETCHING';
export const DELETE_PSYCHOLOGIST_FULFILLED = 'DELETE_PSYCHOLOGIST_FULFILLED';
export const DELETE_PSYCHOLOGIST_REJECTED = 'DELETE_PSYCHOLOGIST_REJECTED';

export const CLOSE_ERROR_MODAL_PSYCHOLOGISTS = 'CLOSE_ERROR_MODAL_PSYCHOLOGISTS';

// Sessions
export const GET_SESSIONS_FETCHING = 'GET_SESSIONS_FETCHING';
export const GET_SESSIONS_FULFILLED = 'GET_SESSIONS_FULFILLED';
export const GET_SESSIONS_REJECTED = 'GET_SESSIONS_REJECTED';

export const GET_SESSION_BY_ID_FETCHING = 'GET_SESSION_BY_ID_FETCHING';
export const GET_SESSION_BY_ID_FULFILLED = 'GET_SESSION_BY_ID_FULFILLED';
export const GET_SESSION_BY_ID_REJECTED = 'GET_SESSION_BY_ID_REJECTED';

export const CREATE_SESSION_FETCHING = 'CREATE_SESSION_FETCHING';
export const CREATE_SESSION_FULFILLED = 'CREATE_SESSION_FULFILLED';
export const CREATE_SESSION_REJECTED = 'CREATE_SESSION_REJECTED';

export const UPDATE_SESSION_FETCHING = 'UPDATE_SESSION_FETCHING';
export const UPDATE_SESSION_FULFILLED = 'UPDATE_SESSION_FULFILLED';
export const UPDATE_SESSION_REJECTED = 'UPDATE_SESSION_REJECTED';

export const DELETE_SESSION_FETCHING = 'DELETE_SESSION_FETCHING';
export const DELETE_SESSION_FULFILLED = 'DELETE_SESSION_FULFILLED';
export const DELETE_SESSION_REJECTED = 'DELETE_SESSION_REJECTED';

export const CLOSE_ERROR_MODAL_SESSIONS = 'CLOSE_ERROR_MODAL_SESSIONS';
//POSTULANTS
export const GET_POSTULANTS_FETCHING = 'GET_POSTULANTS_FETCHING';
export const GET_POSTULANTS_FULFILLED = 'GET_POSTULANTS_FULFILLED';
export const GET_POSTULANTS_REJECTED = 'GET_POSTULANTS_REJECTED';

export const GET_POSTULANT_BY_ID_FETCHING = 'GET_POSTULANT_BY_ID_FETCHING';
export const GET_POSTULANT_BY_ID_FULFILLED = 'GET_POSTULANT_BY_ID_FULFILLED';
export const GET_POSTULANT_BY_ID_REJECTED = 'GET_POSTULANT_BY_ID_REJECTED';

export const CREATE_POSTULANT_FETCHING = 'CREATE_POSTULANT_FETCHING';
export const CREATE_POSTULANT_FULFILLED = 'CREATE_POSTULANT_FULFILLED';
export const CREATE_POSTULANT_REJECTED = 'CREATE_POSTULANT_REJECTED';

export const UPDATE_POSTULANT_FETCHING = 'UPDATE_POSTULANT_FETCHING';
export const UPDATE_POSTULANT_FULFILLED = 'UPDATE_POSTULANT_FULFILLED';
export const UPDATE_POSTULANT_REJECTED = 'UPDATE_POSTULANT_REJECTED';

export const DELETE_POSTULANT_FETCHING = 'DELETE_POSTULANT_FETCHING';
export const DELETE_POSTULANT_FULFILLED = 'DELETE_POSTULANT_FULFILLED';
export const DELETE_POSTULANT_REJECTED = 'DELETE_POSTULANT_REJECTED';

export const CLOSE_ERROR_MODAL_POSTULANTS = 'CLOSE_ERROR_MODAL_POSTULANTS';
