// Admins

// Applications

// Clients

//Interviews

//Positions

//Postulants

//Profiles
export const GET_PROFILES_FETCHING = 'GET_PROFILES_FETCHING';
export const GET_PROFILES_FULFILLED = 'GET_PROFILES_FULFILLED';
export const GET_PROFILES_REJECTED = 'GET_PROFILES_REJECTED';

export const GET_PROFILE_BY_ID_FETCHING = 'GET_PROFILE_BY_ID_FETCHING';
export const GET_PROFILE_BY_ID_FULFILLED = 'GET_PROFILE_BY_ID_FULFILLED';
export const GET_PROFILE_BY_ID_REJECTED = 'GET_PROFILE_BY_ID_REJECTED';

export const CREATE_PROFILE_FETCHING = 'CREATE_PROFILE_FETCHING';
export const CREATE_PROFILE_FULFILLED = 'CREATE_PROFILE_FULFILLED';
export const CREATE_PROFILE_REJECTED = 'CREATE_PROFILE_REJECTED';

export const UPDATE_PROFILE_FETCHING = 'UPDATE_PROFILE_FETCHING';
export const UPDATE_PROFILE_FULFILLED = 'UPDATE_PROFILE_FULFILLED';
export const UPDATE_PROFILE_REJECTED = 'UPDATE_PROFILE_REJECTED';

export const DELETE_PROFILE_FETCHING = 'DELETE_PROFILE_FETCHING';
export const DELETE_PROFILE_FULFILLED = 'DELETE_PROFILE_FULFILLED';
export const DELETE_PROFILE_REJECTED = 'DELETE_PROFILE_REJECTED';

export const CLOSE_ERROR_MODAL_PROFILES = 'CLOSE_ERROR_MODAL_PROFILES';

//Psychologists

//Sessions
